### ISSUE TITLE
是否可以补充小鹤的ok拼字模式？

### ISSUE THREAD

**Issue by Lepton-Lee** [gaboolic/rime-config#125]
小鹤的ok拼字模式有87890字，比目前的az模式全很多。
[导出 - 主码 - 拼字.txt](https://github.com/user-attachments/files/18240667/-.-.txt)

**Comment by gaboolic** [comment]
其实两分支持的字也很多
az模式的字典我之前也贡献过ids版本的，只是需要人工review 没人能做这个事 https://github.com/mirtlecn/rime-radical-pinyin

ok拼字模式也不懂它的拆分规则是怎样的，随便找了几个字都没有 比如“聮”，看上去和两分差不多，实用性不强，比如𮮻	okwfgser  该打不出来还是打不出来。

现在最实用的其实是amq 墨奇码拆字模式，知道墨奇码的拆分规则就能打。比如“聮” (amq)eyyh

**Comment by gaboolic** [comment]
![image](https://github.com/user-attachments/assets/53449db1-f73e-4cd0-ba3e-c67f32c212b9)
