### ISSUE TITLE
[Feature] releases `rime-flypy-flypy` 加上 `radical_flypy` 方案词库

### ISSUE THREAD

**Issue by MajoSissi** [gaboolic/rime-config#86]
除all以外的都不带"az部件组字" 方案词库文件，希望能加上

**Comment by gaboolic** [comment]
把[rime-reverse-and-english-and-emoji.zip](https://github.com/gaboolic/rime-shuangpin-fuzhuma/releases/download/0.0.10/rime-reverse-and-english-and-emoji.zip)  也复制过去解压缩就行了
要加的话得下次
